version: "2.1"

services:

  gradle-embedded-kafka-app:
    build:
      context: .
      dockerfile: gradle/Dockerfile
    environment:
      KAFKA_TOPICS: 'ololololo,trololololo'
      ZOOKEEPER_DIR: './zk'
    volumes: ["gradle-embedded-kafka-app-data:/home"]
    ports: ["8080:8080"]
    networks: [backing-services]
#    mem_limit: 786432000 # container limit: 700Mb (700 * 1024 * 1024)

volumes:
  gradle-embedded-kafka-app-data: {}

networks:
  backing-services:
    driver: bridge
